### ISSUE TITLE
Popular tags::lower popularity count when user unfollows

### ISSUE THREAD

**Issue by PereRohit** [ankitkumbhar/article-tag#1]
## ISSUE
When the user unfollows a tag(s), the popularity for the tag(s) must be lowered.

Similar logic when incrementing the popularity count can be done for deletion: https://github.com/ankitkumbhar/article-tag/blob/56d391dd61e5280197d5a960518f517ba6e57829/internal/model/tag.go#L189

**Comment by ankitkumbhar** [comment]
Closes afb38ba3e2aee7f0d654a53aee246c075592eb4c
