### ISSUE TITLE
Popular tags::show correct popular tags not already followed by user

### ISSUE THREAD

**Issue by PereRohit** [ankitkumbhar/article-tag#6]
## ISSUE
When hitting the popular tags endpoint, without any `username` we get 4 tags(say).
4 is the configured maximum number of tags to be sent from the popular tags endpoint response 
##### Response
```json
{
  "tags": ["tag1", "tag2", "tag3", "tag4"]
}
```
## EXPECTATION
When the `username` is given, the list of followed tags must be avoided but still give 4 tags from the popular tags endpoint.
##### Response
```json
{
  "tags": ["tag4", "tag5", "tag6", "tag7"]
}
```
Assuming the user already follows `tag1`, `tag2` & `tag3`

**Comment by ankitkumbhar** [comment]
Closes 92f0fb08732400a95d863c96e3c6770b14539c7f
